### ISSUE TITLE
Latest Articles Template Max Length

### ISSUE THREAD

**Issue by cklenk** [ventrian/News-Articles#47] opened 2020-07-20 20:03 UTC
I've noticed that when trying to edit the html body template for latest articles it has it set for 50 characters. That is not nearly long enough to properly edit a html template. You can get past it by removing the client side validation and then you can edit it as you wish. Anything in the works to update that, or should we pull request?

Thanks
Cameron

**Comment by Timo-Breumelhof** [comment] 2020-07-21 08:07
This is the same as this issue, right?
https://github.com/ventrian/News-Articles/issues/32

**Comment by cklenk** [comment] 2020-07-21 13:22
@Timo-Breumelhof Thank you, yes that looks like the same issue! We will edit those template files and let you know how it goes.

**Comment by Timo-Breumelhof** [comment] 2020-07-21 13:33
@cklenk  ok good, some extra feedback would be nice. We will add this to a new release if it fixed your issue

**Comment by Timo-Breumelhof** [comment] 2020-10-28 14:21
Duplicate of #32

**Closed by Timo-Breumelhof** 2020-10-28 14:21 UTC
